path: C:/Users/CP1/Documents/GitHub/Consignment-Itemized-Data/CID-yolov8
train: train.txt # train images
val: valid.txt # val images

# Classes
nc: 1 # Number of classes
names: ['Table']  # List of class names